image:
  repository: localstack/localstack-pro
  tag: latest

service:
  type: LoadBalancer
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  externalTrafficPolicy: Local
  edgeService:
    name: edge
    targetPort: 4566
  externalServicePorts:
    start: 4510
    end: 4550

mountDind:
  enabled: false

debug: true

lambda:
  executor: "kubernetes"
  # works with and without
  # securityContext:
  #   runAsUser: 1000

extraEnvVars:
  - name: LOCALSTACK_K8S_SERVICE_NAME
    value: localstack
  - name: LOCALSTACK_K8S_NAMESPACE
    value: default
  - name: LOCALSTACK_API_KEY
    value: <key>
  - name: DNS_ADDRESS
    value: "0"
  - name: LAMBDA_RUNTIME_IMAGE_MAPPING
    value: "{\"python3.9\": \"localstack/lambda-cve-mitigated-python:3.9\"}"
