image:
  repository: localstack/localstack-pro
  tag: latest

service:
  type: LoadBalancer
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  externalTrafficPolicy: Local
  edgeService:
    name: edge
    targetPort: 4566
  externalServicePorts:
    start: 4510
    end: 4550

# breaks when set
# securityContext:
#   runAsUser: 1000

mountDind:
  enabled: true
  forceTLS: true

debug: true

extraEnvVars:
  - name: LAMBDA_RUNTIME_EXECUTOR
    value: docker
  - name: DNS_ADDRESS
    value: "0"
  - name: LAMBDA_DOCKER_NETWORK
    value: "bridge"
  - name: LOCALSTACK_API_KEY
    value: <key>
